const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const config = require('../conference-sources');
const { extractOfficialHtml } = require('../scripts/auto-updater/extract');
const { assess, applyChanges, setField } = require('../scripts/auto-updater/policy');
const { loadEvents, validateEvents, mergeReview } = require('../scripts/auto-updater/storage');
const { validRegistration } = require('../scripts/auto-updater/registration');
const reviewModel = require('../review-model');
const root = path.resolve(__dirname, '..');
const context = vm.createContext({ assert, console, setTimeout, clearTimeout,
  document: { getElementById: () => null, addEventListener: () => {} } });
for (const file of ['venues.js', 'companies.js', 'events.js', 'script.js']) vm.runInContext(fs.readFileSync(path.join(root, file), 'utf8'), context);
vm.runInContext(`
  getTodayString = () => '2026-10-07';
  const event = sampleEvents.find(e => e.id === 'conf-jp-jrvs-2026');
  const html = renderRegistrationHtml(event);
  assert.ok(html.includes('事前参加登録：</span><span class="conf-val deadline-highlight">2026年10月16日まで'));
  assert.ok(html.includes('直前・当日登録：</span><span class="conf-val deadline-highlight">2026年11月12日開始'));
  assert.ok(!html.includes('締切済'));
  assert.ok(!createEventCardHtml(event).includes('早期登録締切'));
  assert.ok(renderRegistrationHtml(event, '2026-10-16').includes('2026年10月16日まで'));
  assert.ok(renderRegistrationHtml(event, '2026-10-17').includes('2026年10月16日 締切済'));
  const pastDeadline = renderRegistrationHtml(event, '2026-10-17');
  assert.ok(pastDeadline.includes('deadline-highlight closed">2026年10月16日 締切済'));
  assert.ok(pastDeadline.includes('deadline-highlight">2026年11月12日開始'));
  assert.equal((pastDeadline.match(/conf-registration-period/g) || []).length, 2);
  assert.ok(!renderRegistrationHtml(event, '2026-10-16').includes('deadline-highlight closed'));
  assert.ok(renderRegistrationHtml(event, '2026-11-12').includes('2026年12月6日まで'));
  assert.ok(renderRegistrationHtml(event, '2026-12-07').includes('2026年12月6日 締切済'));
  const international = { ...event, conferenceRegion: 'international', registration: { type: 'international', periods: [
    { label: 'Early bird', deadline: '2027-03-31' }, { label: 'Regular', deadline: '2027-06-30' },
    { label: 'Late', start: '2027-07-01' }, { label: 'On-site', start: '2027-07-10' }
  ] } };
  const overseas = renderRegistrationHtml(international, '2027-04-01');
  assert.ok(overseas.includes('Early bird：</span><span class="conf-val deadline-highlight closed">2027年3月31日 締切済'));
  assert.ok(overseas.includes('Regular：</span><span class="conf-val deadline-highlight">2027年6月30日まで'));
  assert.ok(overseas.includes('Late') && overseas.includes('On-site'));
  const closedOverseas = renderRegistrationHtml(international, '2027-07-01');
  assert.ok(closedOverseas.includes('deadline-highlight closed">2027年6月30日 締切済'));
  const closedLate = renderRegistrationHtml({ ...international, registration: { type: 'international', periods: [{ label: 'Late', deadline: '2027-07-09' }] } }, '2027-07-10');
  assert.ok(closedLate.includes('deadline-highlight closed">2027年7月9日 締切済'));
  assert.ok(renderRegistrationHtml({ ...event, registration: undefined, earlyRegistrationDeadline: '2026-10-16' }).includes('2026年10月16日まで'));
  assert.ok(renderRegistrationHtml({ ...event, registration: undefined, earlyRegistrationDeadline: '2026-10-01' }).includes('2026年10月1日 締切済'));
  assert.ok(renderRegistrationHtml({ ...event, registration: undefined, earlyRegistrationDeadline: '2026-10-01' }).includes('deadline-highlight closed'));
  assert.ok(renderRegistrationHtml({ ...event, registration: undefined, earlyBirdDeadline: '締切済' }).includes('deadline-highlight closed'));
  assert.ok(renderRegistrationHtml({ ...event, registration: undefined, earlyBirdDeadline: '2026年10月16日(金)' }).includes('2026年10月16日まで'));
  assert.ok(renderRegistrationHtml({ ...event, registration: undefined }).includes('事前参加登録'));
  assert.ok(renderRegistrationHtml({ ...international, registration: undefined }).includes('Early bird'));
  const unsafe = { ...event, registration: { type: 'domestic', periods: [{ label: '<script>', deadline: '2026-10-16' }] } };
  assert.ok(renderRegistrationHtml(unsafe).includes('&lt;script&gt;'));
  assert.ok(renderRegistrationHtml({ ...event, registration: { type: 'domestic', periods: [{ label: '事前参加登録', deadline: 'invalid' }] } }).includes('要確認'));
`, context);

const dataset = loadEvents(root);
const event = dataset.events.find(e => e.id === 'conf-jp-jrvs-2026');
const source = config.sources.find(s => s.id === event.id);
const page = source.pages.find(p => p.role === 'registration');
const official = extractOfficialHtml({ ...page, html: fs.readFileSync(path.join(__dirname, 'fixtures/auto-updater/conf-jp-jrvs-2026-registration.html'), 'utf8') }, source);
const candidate = official.candidates.find(c => c.field === 'registration');
assert.deepEqual(candidate.value, event.registration);
assert.equal(candidate.value.periods.length, 2);
assert.ok(!official.candidates.some(c => c.field.startsWith('abstractSubmission')));
const decide = (candidates, current = event) => assess(current, source, candidates, [], config.defaults, { today: '2026-10-07' });
assert.equal(decide([candidate]).review.length, 0);
const edited = structuredClone(candidate);
edited.value.periods[0].deadline = '2026-10-23';
assert.equal(decide([edited]).review[0].reason, 'deadline-extension-possible');
assert.equal(decide([edited]).review[0].extended, true);
edited.value.periods[0].deadline = '2026-10-09';
assert.equal(decide([edited]).review[0].reason, 'deadline-change-needs-review');
assert.equal(decide([candidate, edited]).review[0].reason, 'multiple-candidates');
const legacy = { ...event, registration: undefined, earlyRegistrationDeadline: '2026-10-01' };
assert.equal(decide([candidate], legacy).review[0].reason, 'deadline-extension-possible');
const fresh = decide([candidate], { ...event, registration: undefined });
assert.equal(fresh.accepted.length, 0);
assert.equal(fresh.review[0].reason, 'registration-periods-needs-review');
assert.throws(() => applyChanges(dataset.events, [{ ...edited, eventId: event.id }]), /manual review/);
const manuallyApproved = structuredClone(event);
setField(manuallyApproved, 'registration', edited.value);
assert.deepEqual(manuallyApproved.registration, edited.value);
assert.ok(!validRegistration({ type: 'domestic', periods: [{ label: '事前参加登録', deadline: '2026-02-30' }] }));
assert.ok(!validRegistration({ type: 'domestic', periods: [{ label: '事前参加登録', start: '2026-11-12', deadline: '2026-10-16' }] }));
assert.throws(() => validateEvents([{ ...event, registration: { type: 'domestic', periods: [] } }]), /registration/);

const internationalSource = { ...source, id: 'conf-int-test', name: 'International Congress', registrationType: 'international', year: 2027, identity: ['International Congress'] };
const foreign = extractOfficialHtml({ role: 'registration', url: page.url, html: '<html><title>International Congress</title><table><tr><th>Early bird</th><td>March 31, 2027</td></tr><tr><th>Regular</th><td>2027-04-01 – 2027-06-30</td></tr><tr><th>Late</th><td>1 July 2027 – 9 July 2027</td></tr><tr><th>On-site</th><td>2027-07-10</td></tr></table></html>' }, internationalSource);
const foreignCandidate = foreign.candidates.find(c => c.field === 'registration');
assert.deepEqual(foreignCandidate.value.periods.map(p => p.label), ['Early bird', 'Regular', 'Late', 'On-site']);
assert.equal(foreignCandidate.value.periods[0].deadline, '2027-03-31');
assert.equal(foreignCandidate.value.periods[1].start, '2027-04-01');
assert.equal(foreignCandidate.value.periods[2].deadline, '2027-07-09');
const inline = extractOfficialHtml({ role: 'registration', url: page.url, html: '<html><title>International Congress</title><h2>Registration</h2><p>Early bird: 2027-03-31 Regular: 2027-06-30 Late: 2027-07-09 On-site: 2027-07-10</p></html>' }, internationalSource);
assert.equal(inline.candidates.find(c => c.field === 'registration').value.periods.length, 4);
const multiline = extractOfficialHtml({ role: 'registration', url: page.url, html: '<html><title>第65回日本網膜硝子体学会総会</title><h2>参加登録期間</h2><p>事前参加登録<br>2026年5月19日正午～10月16日<br>直前・当日登録<br>2026年11月12日正午～12月6日</p></html>' }, source);
assert.deepEqual(multiline.candidates.find(c => c.field === 'registration').value, event.registration);
const conflictHtml = extractOfficialHtml({ role: 'registration', url: page.url, html: '<html><title>第65回日本網膜硝子体学会総会</title><h2>事前参加登録</h2><p>2026年5月19日～10月16日<br>2026年5月19日～10月23日</p></html>' }, source);
assert.equal(conflictHtml.candidates.find(c => c.field === 'registration').value.periods.length, 2);
assert.equal(decide(conflictHtml.candidates).review[0].reason, 'multiple-candidates');
const ambiguous = structuredClone(candidate);
ambiguous.value.periods.push({ ...ambiguous.value.periods[0], deadline: '2026-10-30' });
assert.equal(decide([ambiguous]).review[0].reason, 'multiple-candidates');
assert.equal(decide([{ ...candidate, url: 'https://untrusted.example/' }]).review[0].reason, 'untrusted-evidence-url');
const queue = mergeReview({ version: 1, items: [] }, fresh.review.map(item => ({ ...item, eventId: event.id })), '2026-10-07T00:00:00Z');
const normalized = reviewModel.normalize(JSON.parse(JSON.stringify(queue)));
assert.ok(normalized[0].actionable);
assert.equal(normalized[0].riskLevel, 'medium');
assert.ok(reviewModel.formatValue('registration', normalized[0].value).includes('直前・当日登録'));
const memory = new Map();
const store = reviewModel.createStore({ getItem: k => memory.get(k), setItem: (k, v) => memory.set(k, v) });
store.decide(normalized[0], 'approved', { reviewerId: 'test-admin' });
assert.deepEqual(store.read().history[0].value.periods, event.registration.periods);
const invalidQueue = reviewModel.normalize({ items: [{ field: 'registration', reason: 'invalid-registration', url: page.url, value: { type: 'domestic', periods: [null] } }] });
assert.equal(invalidQueue[0].actionable, false);
assert.ok(reviewModel.formatValue('registration', invalidQueue[0].value).includes('名称未確認'));
console.log('PASS: domestic registration, deadline boundaries, next stage, overseas stages, both legacy fields, JRVS on 2026-10-07, extraction, ambiguity, extension/change review, validation and admin decisions');
