const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {extractFacts,compareEvent,CATEGORIES}=require('../scripts/audit-event-metadata');
const {loadEvents,mergeReview}=require('../scripts/auto-updater/storage');
const {applyReviewedMetadata}=require('../scripts/apply-reviewed-event-metadata');
const model=require('../review-model');
const root=path.resolve(__dirname,'..'),original=fs.readFileSync(path.join(root,'events.js'),'utf8');
const event=require('../reports/event-metadata-audit-2026-10-09.json').records.find(e=>e.eventId==='conf-jp-presbyopia-2027').currentSnapshot;
const url='https://www.rousi.jp/jps4';
// Scoped official overview fixture; explicit year and abbreviated second day.
const html='<html><title>第4回 - 概要 | 日本老視学会</title><h1>日本老視学会 第4回学術総会</h1><h3>テーマ</h3><p>アンメットニーズはここにある</p><h3>日程</h3><p>2026年 1月17日（土）、18日（日）</p><h3>会場</h3><p>品川THE GRAND HALL</p><p>〒108-0075 東京都港区港南2-16-4</p><h3>単位</h3><p>未定</p></html>';
async function main(){
  const extracted=extractFacts(html,event,url),record=compareEvent(event,extracted.facts,url);
  assert.equal(record.category,'possible-wrong-edition');assert.equal(record.priority,'高');
  for(const field of ['title','year','date','endDate','venue','subtitle','eventOfficialUrl'])assert.ok(record.differences.some(d=>d.field===field),field);
  assert.equal(record.comparisons.find(c=>c.field==='title').result,'notation-difference');
  assert.equal(extracted.facts.date.value,'2026-01-17');assert.equal(extracted.facts.endDate.value,'2026-01-18');
  assert.equal(extracted.facts.venue.value,'品川THE GRAND HALL');
  const registration=extractFacts(html,event,url,'event','registration');assert.equal(registration.facts.venue,undefined);
  const mixed=extractFacts('<html><p>SOE 2027 Congress</p><h2>SOE 2025</h2></html>',{...event,title:'SOE 2027 (European Society of Ophthalmology Congress)'},'https://soe2027.soevision.org/');
  assert.equal(mixed.facts.year,undefined);
  const incomplete=compareEvent(event,{},null);assert.equal(incomplete.category,'insufficient-evidence');assert.equal(incomplete.uncheckedFields.length,12);
  assert.equal(compareEvent(event,{},null,[{kind:'index',botProtected:true}]).category,'insufficient-evidence');
  assert.equal(compareEvent(event,{},url,[{kind:'event',botProtected:true}]).category,'bot-protected-official-candidate');
  const complete={};for(const field of ['title','edition','year','date','endDate','cityCountry','venue','sponsor','subtitle'])complete[field]={value:record.comparisons.find(c=>c.field===field)?.current,url,confidence:.97,evidence:'fixture'};
  assert.equal(compareEvent(event,complete,url).category,'official-url-missing');
  assert.equal(compareEvent({...event,eventOfficialUrl:url},complete,url).category,'verified');
  const bad=extractFacts('<html><h1>第4回日本老視学会学術総会</h1><h3>会期</h3><p>2027年2月29日～30日</p></html>',event,url);assert.equal(bad.facts.date,undefined);
  const report=JSON.parse(fs.readFileSync(path.join(root,'reports/event-metadata-audit-2026-10-09.json')));
  assert.equal(report.records.length,94);assert.equal(new Set(report.records.map(r=>r.eventId)).size,94);
  assert.equal(Object.values(report.summary).reduce((a,b)=>a+b,0),94);
  assert.ok(report.records.every(r=>CATEGORIES.includes(r.category)&&r.comparisons.length===12));
  const temp=fs.mkdtempSync(path.join(os.tmpdir(),'metadata-review-test-'));const fixtureData=loadEvents(root);fixtureData.events[fixtureData.events.findIndex(e=>e.id===event.id)]=event;fs.writeFileSync(path.join(temp,'events.js'),fixtureData.serialize(fixtureData.events));fs.mkdirSync(path.join(temp,'reports'));
  const value=Object.fromEntries(record.differences.filter(c=>!['year','edition'].includes(c.field)).map(c=>[c.field,c.official]));
  const queue=mergeReview({items:[]},[{eventId:event.id,field:'eventMetadata',value,oldValue:event,reviewSnapshot:event,audit:record,priority:'高',url,confidence:.97,requiresHumanApproval:true,reason:'metadata-audit-possible-wrong-edition'}],'2026-10-09T00:00:00Z');
  fs.writeFileSync(path.join(temp,'reports/auto-update-review.json'),JSON.stringify(queue));
  const items=model.normalize(queue),memory=new Map(),store=model.createStore({getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v)});
  assert.ok(items[0].actionable);assert.equal(items[0].riskLevel,'high');
  assert.throws(()=>applyReviewedMetadata({root:temp,approvals:store.exportMetadataApprovals(items,'human'),apply:true}),/approval export/);
  store.decide(items[0],'approved',{reviewerId:'human',items,automationCandidate:true});
  assert.equal(store.latest(items[0],'human').automationCandidate,false);
  const approvals=store.exportMetadataApprovals(items,'human');
  applyReviewedMetadata({root:temp,approvals});assert.equal(fs.readFileSync(path.join(temp,'events.js'),'utf8'),fixtureData.serialize(fixtureData.events));
  const tampered=structuredClone(approvals);tampered.decisions[0].value.date='2020-01-01';
  assert.throws(()=>applyReviewedMetadata({root:temp,approvals:tampered,apply:true}),/stale|mismatched/);
  applyReviewedMetadata({root:temp,approvals,apply:true});
  const updated=loadEvents(temp).events.find(e=>e.id===event.id);assert.equal(updated.date,'2026-01-17');assert.equal(updated.venue,'品川THE GRAND HALL');assert.equal(updated.id,event.id);
  assert.ok(updated.period.includes('2026年1月17日'));assert.equal(updated.subtitle,'アンメットニーズはここにある');
  const geoData=loadEvents(root),geoEvent=geoData.events.find(e=>e.id===event.id);
  Object.keys(geoEvent).forEach(k=>delete geoEvent[k]);Object.assign(geoEvent,structuredClone(event));geoEvent.venueId='fixture-old-venue';geoEvent.timeZone='Asia/Singapore';
  const geoTemp=fs.mkdtempSync(path.join(os.tmpdir(),'metadata-geo-test-'));fs.writeFileSync(path.join(geoTemp,'events.js'),geoData.serialize(geoData.events));fs.mkdirSync(path.join(geoTemp,'reports'));
  const geoQueue=mergeReview({items:[]},[{...queue.items[0],oldValue:geoEvent,reviewSnapshot:geoEvent}],'2026-10-09T00:00:00Z');
  fs.writeFileSync(path.join(geoTemp,'reports/auto-update-review.json'),JSON.stringify(geoQueue));
  const geoItems=model.normalize(geoQueue);store.decide(geoItems[0],'approved',{reviewerId:'human',items:geoItems});
  applyReviewedMetadata({root:geoTemp,approvals:store.exportMetadataApprovals(geoItems,'human'),apply:true});
  const geoUpdated=loadEvents(geoTemp).events.find(e=>e.id===event.id);assert.equal(geoUpdated.venueId,undefined);assert.equal(geoUpdated.timeZone,undefined);
  assert.equal(fs.readFileSync(path.join(root,'events.js'),'utf8'),original);
  console.log('PASS: JPS4 seven differences (title/year/two dates/venue/theme/URL), notation vs misinformation, scope guards, 94-record coverage, no automatic mutation, human-only atomic metadata apply, stale approval rejection and ID preservation');
}
main().catch(e=>{console.error(e);process.exitCode=1;});
