const assert = require('node:assert/strict');
const model = require('../review-model');
const { createProvider } = require('../review-data');
const fixture = require('./fixtures/review/auto-update-review.json');
async function main() {
  const items = model.normalize(fixture);
  assert.equal(items.filter(i => !i.blocked).length, 9);
  assert.equal(items.filter(i => i.blocked).length, 11);
  const low = items.find(i => i.riskLevel === 'low');
  assert.ok(low);
  for (const field of ['title', 'date', 'endDate', 'venue', 'city', 'country']) assert.equal(model.riskLevel({ ...low, field }), 'high');
  assert.equal(model.riskLevel({ ...low, field: 'officialUrl', oldValue: 'https://a.example/', value: 'https://b.example/' }), 'high');
  assert.equal(model.riskLevel({ ...low, reason: 'multiple-candidates' }), 'medium');
  assert.equal(model.riskLevel({ ...low, reason: 'low-confidence' }), 'medium');
  assert.equal(model.riskLevel({ ...low, confidence: 0.5 }), 'medium');
  assert.equal(model.riskLevel({ ...low, oldValue: 'existing' }), 'medium');
  assert.equal(model.safeUrl('javascript:alert(1)'), null);
  assert.equal(model.createAccess({ hostname: 'example.com', search: '?adminReview=1' }).reviewerId({ uid: 'any' }), null);
  assert.equal(model.createAccess({ hostname: 'localhost', search: '?adminReview=1' }).reviewerId(null), null);
  assert.equal(model.createAccess({ hostname: 'localhost', search: '?adminReview=1', developmentMode: true }).reviewerId(null), 'local-admin');
  assert.equal(model.createAccess({ hostname: 'example.com', search: '?adminReview=1', developmentMode: true }).reviewerId(null), null);
  assert.equal(model.createAccess({ hostname: 'localhost', search: '' }).reviewerId(null), null);
  const uidAccess = model.createAccess({ hostname: 'example.com', search: '', authorizeUser: user => user.uid === 'admin' });
  assert.equal(uidAccess.reviewerId({ uid: 'admin' }), 'admin');
  assert.equal(uidAccess.reviewerId(null), null);
  const memory = new Map(), storage = { getItem: key => memory.get(key), setItem: (key, value) => memory.set(key, value) };
  const store = model.createStore(storage), context = { reviewerId: 'local-admin', items };
  store.decide(low, 'approved', { ...context, automationCandidate: true });
  assert.equal(model.createStore(storage).latest(low, 'local-admin').decision, 'approved');
  assert.equal(store.latest(low, 'other'), undefined);
  assert.equal(store.latest({ ...low, signature: 'changed-candidate' }, 'local-admin'), undefined);
  store.decide(low, 'rejected', context); store.decide(low, 'deferred', context);
  assert.equal(store.statistics(low, 'local-admin').approvalCount, 1);
  assert.equal(store.statistics(low, 'local-admin').hasRejection, true);
  assert.equal(store.latest(low, 'local-admin').decision, 'deferred');
  const conflict = items.filter(i => i.reason === 'multiple-candidates' && i.field === 'abstractSubmission.deadline');
  store.decide(conflict[0], 'approved', context);
  assert.throws(() => store.decide(conflict[1], 'approved', context), /別候補/);
  store.decide(conflict[0], 'rejected', context);
  store.decide(conflict[1], 'approved', { ...context, automationCandidate: true });
  assert.equal(store.latest(conflict[1], 'local-admin').automationCandidate, false);
  assert.throws(() => store.decide({ ...low, actionable: false }, 'approved', context));
  assert.throws(() => model.createStore({ getItem: () => '{bad' }).read());
  assert.throws(() => model.createStore({ getItem: () => null, setItem: () => { throw new Error('quota'); } }).decide(low, 'approved', context), /quota/);
  assert.equal((await createProvider({ fetchImpl: async () => ({ ok: true, json: async () => fixture }) }).load()).items.length, 20);
  let requestedUrl;
  await createProvider({ fetchImpl: async url => { requestedUrl = url; return { ok: true, json: async () => fixture }; } }).load();
  assert.equal(requestedUrl, 'reports/auto-update-review.json');
  await assert.rejects(createProvider({ fetchImpl: async () => ({ ok: false }) }).load());
  await assert.rejects(createProvider({ fetchImpl: async () => ({ ok: true, json: async () => ({ items: [] }) }) }).load());
  console.log('PASS: review fixture separation, risks, access, decisions, persistence, history, conflicts, safe URLs, storage errors and provider');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
